[package]
name = "hasilan-bitwarden-compat"
description = "Bitwarden JSON import and export compatibility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
hasilan-vault = { path = "../vault" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true

